# File: .github/workflows/repo-sync.yml

on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://code.ill.fr/rodriguez-carvajal/CrysFML2008.git"
        source_branch: "*"
        destination_branch: "*"
        github_token: ${{ secrets.PAT }}
